"""empty message

Revision ID: 89e9bef00bdc
Revises: 
Create Date: 2020-12-06 13:43:27.527204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89e9bef00bdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disasters', 'disaster_type',
               existing_type=postgresql.ENUM('EARTHQUAKE', 'FLOOD', 'WILDFIRE', 'TORNADO', 'HURRICANE', 'TSUNAMI', 'LANDSLIDE', 'AVALANCHE', 'VOLCANO', 'OTHER', name='naturaldisasterenum'),
               nullable=False)
    op.alter_column('disasters', 'official_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disasters', 'official_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('disasters', 'disaster_type',
               existing_type=postgresql.ENUM('EARTHQUAKE', 'FLOOD', 'WILDFIRE', 'TORNADO', 'HURRICANE', 'TSUNAMI', 'LANDSLIDE', 'AVALANCHE', 'VOLCANO', 'OTHER', name='naturaldisasterenum'),
               nullable=True)
    # ### end Alembic commands ###
