"""empty message

Revision ID: c03f8d18e668
Revises: 
Create Date: 2021-08-28 05:59:06.566815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03f8d18e668'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disasters', sa.Column('last_update_datetime', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('witnessreports', sa.Column('last_update_datetime', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('witnessreports', 'last_update_datetime')
    op.drop_column('disasters', 'last_update_datetime')
    # ### end Alembic commands ###
