"""empty message

Revision ID: d332a354ac10
Revises: 9147926c5687
Create Date: 2021-08-28 13:34:08.705416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd332a354ac10'
down_revision = '9147926c5687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disasters', 'informal_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('disasters', 'is_ongoing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disasters', 'is_ongoing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('disasters', 'informal_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
